# gitResource.yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cicd-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/safernandez666/cicd.git
    - name: revision
      value: main