apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: monitoring
type: Opaque
stringData:
  INFLUXDB_DB: influx
  INFLUXDB_URL: http://31b7dfdc0735.ngrok.io
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: admin
